### ISSUE TITLE
undefined method `run_list' for #<Hash:0x0000000166f9d0> (NoMethodError)

### ISSUE THREAD

**Issue by askmike1** [trickyearlobe/knife-pinnings#5] opened 2018-12-11 18:42 UTC
Command:
```
knife pinnings set auto <environment_name>
```

Version:
```
# knife -v
Chef: 13.6.0
```

Output
```
# knife pinnings set auto env_latest -VV
INFO: Using configuration from /root/nashome/chefrepo/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as patam003
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://chef.wdprapps.disney.com/organizations/wdat/environments/recrooms_adapter_dlr_latest
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: patam003
DEBUG: X-OPS-TIMESTAMP: 2018-12-11T18:36:44Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: WXfFjqfdA3pfsHx5n/0cvGTbd20CjRMQJiIZn6O8nKt1eQu8jfW2cQR3xhfc
DEBUG: X-OPS-AUTHORIZATION-2: PgA91JJnRQMG6V9mW2D4h+69A7ObaSTnjwZYht0UkS744qnZs0hxjzJQUd+a
DEBUG: X-OPS-AUTHORIZATION-3: A9eDIy9IPCkY4HFY67mzaEggcVAXI3Z8C7OtnhLfm7LPwtK7iH+7pOIdPeys
DEBUG: X-OPS-AUTHORIZATION-4: KjcYllE4K38ppo8QwxZloMB9KmVYinshriL/HppTDj8E/XVtC+qhQRFMshXD
DEBUG: X-OPS-AUTHORIZATION-5: hbd6p06+Y9mJMzmou30d2DtdendM1k//XsHAjawbm94gEEmpjlrAAOeQbId0
DEBUG: X-OPS-AUTHORIZATION-6: PZIdja8FyGawO91GjGISHjBsEMhIgdZND/s+EkHykw==
DEBUG: HOST: chef.wdprapps.disney.com:443
DEBUG: X-REMOTE-REQUEST-ID: e1dd58da-229e-4569-90d1-ae32e48319a4
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: cache-control: no-cache="set-cookie"
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json
DEBUG: date: Tue, 11 Dec 2018 18:36:44 GMT
DEBUG: server: openresty/1.11.2.1
DEBUG: set-cookie: AWSELB=F7DF2BA71489B34ED9070CDB3B20685F6F656D1531D6A75551ED2F155B382A1EE5EFB96305C38531A352E95A2E7E5176F9EFF0CD023C0993DAA64CE40464D943E22C794AC8;PATH=/
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.16.13+20170918151341
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: content-length: 845
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as patam003
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://chef.wdprapps.disney.com/organizations/wdat/environments/recrooms_adapter_dlr_latest/nodes
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Cookie: AWSELB=F7DF2BA71489B34ED9070CDB3B20685F6F656D1531D6A75551ED2F155B382A1EE5EFB96305C38531A352E95A2E7E5176F9EFF0CD023C0993DAA64CE40464D943E22C794AC8;PATH=/
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: patam003
DEBUG: X-OPS-TIMESTAMP: 2018-12-11T18:36:44Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: jujDJ6AxLa9bu/UK2ICOYiKyJ9I4DO/xIvGeMGMSFyzgB+z5cadSOZQAtZRv
DEBUG: X-OPS-AUTHORIZATION-2: wffGMqFWGc8MoNIowYvwj2cTLkoUqQsj7IVnHxDH8MGefpVMPBG+kw5+BXzS
DEBUG: X-OPS-AUTHORIZATION-3: l50LICsXB/KN0P+G5KcXMW2/4NNAaVeRudcmb9eG1c2NQ29FFrDqbGpASncw
DEBUG: X-OPS-AUTHORIZATION-4: fBTGDcSzHQSajmLBg2B+ULsSjDU5PKtqJ/oVtnt6EgbaVe1FxqUfepjRMl/n
DEBUG: X-OPS-AUTHORIZATION-5: rul59ZNEzkQ7yel8n+Cz7vOQ9loeu02RJbB77VmZ2zezrtJWEjzWhuy9cR+A
DEBUG: X-OPS-AUTHORIZATION-6: m1JZ9UO8MfIi48ayHhxADACjuoXmWhwwWA+Qxbn/5g==
DEBUG: HOST: chef.wdprapps.disney.com:443
DEBUG: X-REMOTE-REQUEST-ID: e1dd58da-229e-4569-90d1-ae32e48319a4
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json
DEBUG: date: Tue, 11 Dec 2018 18:36:44 GMT
DEBUG: server: openresty/1.11.2.1
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.16.13+20170918151341
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: content-length: 105
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
2 nodes have been found in environment recrooms_adapter_dlr_latest: ["fldcvdsla17115", "fldcvdsla17116"]
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as patam003
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://chef.wdprapps.disney.com/organizations/wdat/environments/recrooms_adapter_dlr_latest/nodes
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Cookie: AWSELB=F7DF2BA71489B34ED9070CDB3B20685F6F656D1531D6A75551ED2F155B382A1EE5EFB96305C38531A352E95A2E7E5176F9EFF0CD023C0993DAA64CE40464D943E22C794AC8;PATH=/
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: patam003
DEBUG: X-OPS-TIMESTAMP: 2018-12-11T18:36:44Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: jujDJ6AxLa9bu/UK2ICOYiKyJ9I4DO/xIvGeMGMSFyzgB+z5cadSOZQAtZRv
DEBUG: X-OPS-AUTHORIZATION-2: wffGMqFWGc8MoNIowYvwj2cTLkoUqQsj7IVnHxDH8MGefpVMPBG+kw5+BXzS
DEBUG: X-OPS-AUTHORIZATION-3: l50LICsXB/KN0P+G5KcXMW2/4NNAaVeRudcmb9eG1c2NQ29FFrDqbGpASncw
DEBUG: X-OPS-AUTHORIZATION-4: fBTGDcSzHQSajmLBg2B+ULsSjDU5PKtqJ/oVtnt6EgbaVe1FxqUfepjRMl/n
DEBUG: X-OPS-AUTHORIZATION-5: rul59ZNEzkQ7yel8n+Cz7vOQ9loeu02RJbB77VmZ2zezrtJWEjzWhuy9cR+A
DEBUG: X-OPS-AUTHORIZATION-6: m1JZ9UO8MfIi48ayHhxADACjuoXmWhwwWA+Qxbn/5g==
DEBUG: HOST: chef.wdprapps.disney.com:443
DEBUG: X-REMOTE-REQUEST-ID: e1dd58da-229e-4569-90d1-ae32e48319a4
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json
DEBUG: date: Tue, 11 Dec 2018 18:36:45 GMT
DEBUG: server: openresty/1.11.2.1
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.16.13+20170918151341
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: content-length: 105
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as patam003
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://chef.wdprapps.disney.com/organizations/wdat/nodes/fldcvdsla17115
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Cookie: AWSELB=F7DF2BA71489B34ED9070CDB3B20685F6F656D1531D6A75551ED2F155B382A1EE5EFB96305C38531A352E95A2E7E5176F9EFF0CD023C0993DAA64CE40464D943E22C794AC8;PATH=/
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: patam003
DEBUG: X-OPS-TIMESTAMP: 2018-12-11T18:36:45Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: aJHWaTo9/MRoq4z2o+/uBBtRU0Chf44Qgiy59aqQOJYxezizZ4v8v1fmAiw/
DEBUG: X-OPS-AUTHORIZATION-2: S7TUHHcCU1XHRM9JZtmPmZivJalaFcZn/yDKQp1H9qwiF+4T2O2wGzx2X2Lk
DEBUG: X-OPS-AUTHORIZATION-3: g8KayyaHMAIzh5w9y677ukvaYkXNDf8/mEb0Pzg1VaMuitxHyuP/O459GC3l
DEBUG: X-OPS-AUTHORIZATION-4: 7idjlzqh9GFRbRM2WRaINOOgRL/kJi6QSD2r882lCx7/kWvtqP38dXFIbLcn
DEBUG: X-OPS-AUTHORIZATION-5: 6xckw1BRAeDm2VMYQyOBJOP07HDcBHP0LxtNsXmdDj3jSlHijr4x9IS0hfeR
DEBUG: X-OPS-AUTHORIZATION-6: LCuvJqJotJ6OCYj0nrdafFKJJWA7bVZt6RlUfA2xwA==
DEBUG: HOST: chef.wdprapps.disney.com:443
DEBUG: X-REMOTE-REQUEST-ID: e1dd58da-229e-4569-90d1-ae32e48319a4
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json
DEBUG: date: Tue, 11 Dec 2018 18:36:45 GMT
DEBUG: server: openresty/1.11.2.1
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.16.13+20170918151341
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: transfer-encoding: chunked
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/usr/local/rvm/gems/ruby-2.3.1/gems/knife-pinnings-1.4.3/lib/chef/knife/pinnings_mixin.rb:131:in `block in cookbooks_used_by': undefined method `run_list' for #<Hash:0x0000000166f9d0> (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/knife-pinnings-1.4.3/lib/chef/knife/pinnings_mixin.rb:130:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/knife-pinnings-1.4.3/lib/chef/knife/pinnings_mixin.rb:130:in `cookbooks_used_by'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/knife-pinnings-1.4.3/lib/chef/knife/pinnings_set_auto.rb:40:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/chef-13.6.0/lib/chef/knife.rb:442:in `block in run_with_pretty_exceptions'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/chef-13.6.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/chef-13.6.0/lib/chef/knife.rb:441:in `run_with_pretty_exceptions'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/chef-13.6.0/lib/chef/knife.rb:219:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/chef-13.6.0/lib/chef/application/knife.rb:156:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/chef-13.6.0/bin/knife:25:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/knife:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/knife:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by trickyearlobe** [comment] 2018-12-12 09:14
Hi @askmike1 , what were you doing at the time this failed?
What version of Chef client are you using?

**Comment by askmike1** [comment] 2018-12-13 04:34
Command:
```
knife pinnings set auto <environment_name>
```

Version:
```
# knife -v
Chef: 13.6.0
```

**Comment by askmike1** [comment] 2019-01-14 05:14
Any update on this issue before I attempt my own knife plugin to do the same?

**Comment by trickyearlobe** [comment] 2019-01-14 09:42
Sorry @askmike1 , I've been travelling and haven't had time to work on this. I may get some time this week, but if it's urgent, please feel free to work on something in parallel, or make a PR.

I suspect the issue is that the API has changed slightly for the depsolver.

**Comment by trickyearlobe** [comment] 2020-05-01 11:23
@askmike1 , I did a bit of tidying up to make it work with CC15.
If you didn't get around to writing your own yet, give 1.4.7 or later a try.

It was nothing to do with the depsolver... just some basic stuff thats been tidied up in CC15.

**Comment by trickyearlobe** [comment] 2021-06-11 09:31
Hi @askmike1 
Since feedback from others indicates the fix works well with CC14, CC15, CC16 and CC17 I'm going to close this issue.

Feel free to re-open if you still have issues and didn't switch to your own solution.

**Closed as completed by trickyearlobe** 2021-06-11 09:31 UTC
